//
//  PDFExporter.swift
//  SplitBill
//
//  Created by Alvin Reyvaldo on 26/11/25.
//

import Foundation
import UIKit
import PDFKit

struct PDFExporter {
    static func generateSummaryPDF(
        title: String,
        total: Double,
        average: Double,
        people: [Person],
        items: [BillItem],
        adjustments: [Adjustment]
    ) throws -> URL {
        let pageWidth: CGFloat = 612 // 8.5in
        let pageHeight: CGFloat = 792 // 11in
        let margin: CGFloat = 40
        let brandGreen = UIColor(red: 0.298, green: 0.686, blue: 0.314, alpha: 1.0) // #4CAF50
        let lightGray = UIColor(red: 0.95, green: 0.95, blue: 0.95, alpha: 1.0)
        let darkGray = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1.0)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            let context = ctx.cgContext

            var y: CGFloat = margin
            let maxY: CGFloat = pageHeight - margin - 40 // Leave space for footer

            func checkNewPage() {
                if y > maxY {
                    // Draw footer on current page
                    let footerY = pageHeight - margin - 20
                    _ = drawText("Generated by Split Bill", font: .systemFont(ofSize: 10, weight: .regular), color: darkGray, x: margin, y: footerY, width: pageWidth - 2 * margin, alignment: .center)

                    // Start new page
                    ctx.beginPage()
                    y = margin + 20
                }
            }

            // MARK: - Helper Functions

            func drawRoundedRect(x: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat, radius: CGFloat, fillColor: UIColor, strokeColor: UIColor? = nil) {
                let rect = CGRect(x: x, y: y, width: width, height: height)
                let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
                context.saveGState()
                fillColor.setFill()
                path.fill()
                if let stroke = strokeColor {
                    stroke.setStroke()
                    path.lineWidth = 1
                    path.stroke()
                }
                context.restoreGState()
            }

            func drawCircle(x: CGFloat, y: CGFloat, radius: CGFloat, fillColor: UIColor) {
                let rect = CGRect(x: x - radius, y: y - radius, width: radius * 2, height: radius * 2)
                context.saveGState()
                fillColor.setFill()
                context.fillEllipse(in: rect)
                context.restoreGState()
            }

            func drawText(_ text: String, font: UIFont, color: UIColor, x: CGFloat, y: CGFloat, width: CGFloat, alignment: NSTextAlignment = .left) -> CGFloat {
                let paragraph = NSMutableParagraphStyle()
                paragraph.alignment = alignment
                paragraph.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraph
                ]
                let attributed = NSAttributedString(string: text, attributes: attrs)
                let rect = CGRect(x: x, y: y, width: width, height: .greatestFiniteMagnitude)
                let size = attributed.boundingRect(with: rect.size, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                attributed.draw(with: rect, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                return size.height
            }

            // MARK: - Header with Gradient Background

            // Draw green header background
            drawRoundedRect(x: 0, y: 0, width: pageWidth, height: 140, radius: 0, fillColor: brandGreen)

            // App branding
            let brandHeight = drawText("SPLIT BILL", font: .systemFont(ofSize: 14, weight: .bold), color: .white, x: margin, y: margin, width: pageWidth - 2 * margin)

            // Title
            let titleHeight = drawText(title.isEmpty ? "Bill Summary" : title, font: .systemFont(ofSize: 28, weight: .bold), color: .white, x: margin, y: margin + brandHeight + 12, width: pageWidth - 2 * margin)

            // Date
            let formatter = DateFormatter()
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
            let dateStr = formatter.string(from: Date())
            _ = drawText(dateStr, font: .systemFont(ofSize: 12, weight: .regular), color: UIColor.white.withAlphaComponent(0.9), x: margin, y: margin + brandHeight + titleHeight + 20, width: pageWidth - 2 * margin)

            y = 160

            // MARK: - Summary Cards

            let cardWidth = (pageWidth - 2 * margin - 20) / 2

            // Total Card
            drawRoundedRect(x: margin, y: y, width: cardWidth, height: 100, radius: 12, fillColor: .white, strokeColor: lightGray)
            _ = drawText("TOTAL TO COLLECT", font: .systemFont(ofSize: 11, weight: .semibold), color: darkGray, x: margin + 16, y: y + 16, width: cardWidth - 32, alignment: .left)
            _ = drawText(total.toCurrency(), font: .systemFont(ofSize: 24, weight: .bold), color: .black, x: margin + 16, y: y + 40, width: cardWidth - 32, alignment: .left)

            // Average Card
            drawRoundedRect(x: margin + cardWidth + 20, y: y, width: cardWidth, height: 100, radius: 12, fillColor: .white, strokeColor: lightGray)
            _ = drawText("AVG PER PERSON", font: .systemFont(ofSize: 11, weight: .semibold), color: darkGray, x: margin + cardWidth + 20 + 16, y: y + 16, width: cardWidth - 32, alignment: .left)
            _ = drawText(average.toCurrency(), font: .systemFont(ofSize: 24, weight: .bold), color: .black, x: margin + cardWidth + 20 + 16, y: y + 40, width: cardWidth - 32, alignment: .left)

            y += 120

            // MARK: - People & Items Section

            _ = drawText("PEOPLE & ITEMS", font: .systemFont(ofSize: 13, weight: .bold), color: darkGray, x: margin, y: y, width: pageWidth - 2 * margin)
            y += 30

            for person in people {
                checkNewPage()

                // Person card
                let personCardHeight: CGFloat = 60
                drawRoundedRect(x: margin, y: y, width: pageWidth - 2 * margin, height: personCardHeight, radius: 10, fillColor: lightGray)

                // Avatar circle (green)
                drawCircle(x: margin + 30, y: y + 30, radius: 18, fillColor: brandGreen)
                let initial = String(person.name.prefix(1)).uppercased()
                _ = drawText(initial, font: .systemFont(ofSize: 14, weight: .bold), color: .white, x: margin + 30 - 8, y: y + 30 - 7, width: 16, alignment: .center)

                // Name
                _ = drawText(person.name, font: .systemFont(ofSize: 16, weight: .semibold), color: .black, x: margin + 60, y: y + 18, width: 200, alignment: .left)

                // Amount
                _ = drawText(person.amount.toCurrency(), font: .systemFont(ofSize: 18, weight: .bold), color: .black, x: pageWidth - margin - 150, y: y + 18, width: 140, alignment: .right)

                y += personCardHeight + 12

                // Items for this person
                let personItems = items.filter { $0.personId == person.id }
                if !personItems.isEmpty {
                    for item in personItems {
                        checkNewPage()

                        drawRoundedRect(x: margin + 20, y: y, width: pageWidth - 2 * margin - 40, height: 40, radius: 8, fillColor: .white, strokeColor: lightGray)

                        _ = drawText("• \(item.name)", font: .systemFont(ofSize: 13, weight: .regular), color: .black, x: margin + 36, y: y + 12, width: 300, alignment: .left)

                        let itemText = item.quantity > 1 ? "\(item.price.toCurrency()) x\(item.quantity)" : item.price.toCurrency()
                        _ = drawText(itemText, font: .systemFont(ofSize: 13, weight: .semibold), color: .black, x: pageWidth - margin - 180, y: y + 12, width: 140, alignment: .right)

                        y += 48
                    }
                } else {
                    checkNewPage()
                    drawRoundedRect(x: margin + 20, y: y, width: pageWidth - 2 * margin - 40, height: 40, radius: 8, fillColor: .white, strokeColor: lightGray)
                    _ = drawText("No items", font: .systemFont(ofSize: 13, weight: .regular), color: darkGray, x: margin + 36, y: y + 12, width: 300, alignment: .left)
                    y += 48
                }

                y += 10
            }

            // MARK: - Extras/Adjustments Section

            if !adjustments.isEmpty {
                y += 10
                _ = drawText("EXTRAS", font: .systemFont(ofSize: 13, weight: .bold), color: darkGray, x: margin, y: y, width: pageWidth - 2 * margin)
                y += 30

                for adj in adjustments {
                    drawRoundedRect(x: margin, y: y, width: pageWidth - 2 * margin, height: 50, radius: 10, fillColor: .white, strokeColor: lightGray)

                    _ = drawText(adj.name, font: .systemFont(ofSize: 15, weight: .semibold), color: .black, x: margin + 16, y: y + 12, width: 250, alignment: .left)

                    let adjLabel = adj.isDiscount ? "Discount" : "Charge"
                    _ = drawText(adjLabel, font: .systemFont(ofSize: 11, weight: .regular), color: adj.isDiscount ? .systemRed : darkGray, x: margin + 16, y: y + 30, width: 100, alignment: .left)

                    let adjAmount = (adj.isDiscount ? -adj.amount : adj.amount).toCurrency()
                    _ = drawText(adjAmount, font: .systemFont(ofSize: 16, weight: .bold), color: adj.isDiscount ? .systemRed : .black, x: pageWidth - margin - 150, y: y + 16, width: 140, alignment: .right)

                    y += 60
                }
            }

            // MARK: - Footer

            let footerY = pageHeight - margin - 20
            _ = drawText("Generated by Split Bill", font: .systemFont(ofSize: 10, weight: .regular), color: darkGray, x: margin, y: footerY, width: pageWidth - 2 * margin, alignment: .center)
        }

        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("SplitBill-\(Date().timeIntervalSince1970).pdf")
        try data.write(to: tempURL)
        return tempURL
    }
}
