//
//  PDFExporter.swift
//  SplitBill
//
//  Created by Alvin Reyvaldo on 26/11/25.
//

import Foundation
import UIKit
import PDFKit

struct PDFExporter {
    static func generateSummaryPDF(
        title: String,
        total: Double,
        average: Double,
        people: [Person],
        items: [BillItem],
        adjustments: [Adjustment]
    ) throws -> URL {
        let pageWidth: CGFloat = 612 // 8.5in
        let pageHeight: CGFloat = 792 // 11in
        let margin: CGFloat = 40
        let brandGreen = UIColor(red: 0.145, green: 0.388, blue: 0.922, alpha: 1.0) // #2563EB
        let lightGray = UIColor(red: 0.95, green: 0.95, blue: 0.95, alpha: 1.0)
        let darkGray = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1.0)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            let context = ctx.cgContext

            var y: CGFloat = margin
            let maxY: CGFloat = pageHeight - margin - 40 // Leave space for footer

            func checkNewPage() {
                if y > maxY {
                    // Draw footer on current page
                    let footerY = pageHeight - margin - 20
                    _ = drawText("Generated by Split Bill", font: .systemFont(ofSize: 10, weight: .regular), color: darkGray, x: margin, y: footerY, width: pageWidth - 2 * margin, alignment: .center)

                    // Start new page
                    ctx.beginPage()
                    y = margin + 20
                }
            }

            // MARK: - Helper Functions

            func drawRoundedRect(x: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat, radius: CGFloat, fillColor: UIColor, strokeColor: UIColor? = nil) {
                let rect = CGRect(x: x, y: y, width: width, height: height)
                let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
                context.saveGState()
                fillColor.setFill()
                path.fill()
                if let stroke = strokeColor {
                    stroke.setStroke()
                    path.lineWidth = 1
                    path.stroke()
                }
                context.restoreGState()
            }

            func drawCircle(x: CGFloat, y: CGFloat, radius: CGFloat, fillColor: UIColor) {
                let rect = CGRect(x: x - radius, y: y - radius, width: radius * 2, height: radius * 2)
                context.saveGState()
                fillColor.setFill()
                context.fillEllipse(in: rect)
                context.restoreGState()
            }

            func drawText(_ text: String, font: UIFont, color: UIColor, x: CGFloat, y: CGFloat, width: CGFloat, alignment: NSTextAlignment = .left) -> CGFloat {
                let paragraph = NSMutableParagraphStyle()
                paragraph.alignment = alignment
                paragraph.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraph
                ]
                let attributed = NSAttributedString(string: text, attributes: attrs)
                let rect = CGRect(x: x, y: y, width: width, height: .greatestFiniteMagnitude)
                let size = attributed.boundingRect(with: rect.size, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                attributed.draw(with: rect, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                return size.height
            }

            // MARK: - Header

            let headerH: CGFloat = 130
            drawRoundedRect(x: 0, y: 0, width: pageWidth, height: headerH, radius: 0, fillColor: brandGreen)

            let formatter = DateFormatter()
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
            let dateStr = formatter.string(from: Date())

            // Avatar (left side, vertically centered)
            let avatarR: CGFloat = 38
            let avatarCX: CGFloat = margin + avatarR
            let avatarCY: CGFloat = headerH / 2
            let avatarRect = CGRect(x: avatarCX - avatarR, y: avatarCY - avatarR, width: avatarR * 2, height: avatarR * 2)

            if let profileImg = ProfileImageStore.load() {
                // Clip to circle and draw profile photo
                context.saveGState()
                UIBezierPath(ovalIn: avatarRect).addClip()
                profileImg.draw(in: avatarRect)
                context.restoreGState()
            } else {
                // Fallback: white circle with initial
                context.saveGState()
                UIColor.white.withAlphaComponent(0.25).setFill()
                UIBezierPath(ovalIn: avatarRect).fill()
                context.restoreGState()
                let initial = String((UserDefaults.standard.string(forKey: "userName") ?? "S").prefix(1)).uppercased()
                _ = drawText(initial, font: .systemFont(ofSize: 28, weight: .bold), color: .white,
                             x: avatarCX - avatarR, y: avatarCY - 17, width: avatarR * 2, alignment: .center)
            }

            // White circle border
            context.saveGState()
            UIColor.white.withAlphaComponent(0.4).setStroke()
            let borderPath = UIBezierPath(ovalIn: avatarRect)
            borderPath.lineWidth = 1.5
            borderPath.stroke()
            context.restoreGState()

            // Right side text: SPLITIN → bill name → date
            let textX    = avatarCX + avatarR + 16
            let textW    = pageWidth - textX - margin
            _ = drawText("SPLITIN", font: .systemFont(ofSize: 11, weight: .bold),
                         color: UIColor.white.withAlphaComponent(0.7), x: textX, y: 24, width: textW)
            _ = drawText(title.isEmpty ? "Bill Summary" : title,
                         font: .systemFont(ofSize: 24, weight: .bold), color: .white,
                         x: textX, y: 42, width: textW)
            _ = drawText(dateStr, font: .systemFont(ofSize: 11, weight: .regular),
                         color: UIColor.white.withAlphaComponent(0.85), x: textX, y: 96, width: textW)

            y = 150

            // MARK: - Summary Cards

            let cardWidth = (pageWidth - 2 * margin - 20) / 2

            // Total Card
            drawRoundedRect(x: margin, y: y, width: cardWidth, height: 100, radius: 12, fillColor: .white, strokeColor: lightGray)
            _ = drawText("TOTAL TO COLLECT", font: .systemFont(ofSize: 11, weight: .semibold), color: darkGray, x: margin + 16, y: y + 16, width: cardWidth - 32, alignment: .left)
            _ = drawText(total.toCurrency(), font: .systemFont(ofSize: 24, weight: .bold), color: .black, x: margin + 16, y: y + 40, width: cardWidth - 32, alignment: .left)

            // Average Card
            drawRoundedRect(x: margin + cardWidth + 20, y: y, width: cardWidth, height: 100, radius: 12, fillColor: .white, strokeColor: lightGray)
            _ = drawText("AVG PER PERSON", font: .systemFont(ofSize: 11, weight: .semibold), color: darkGray, x: margin + cardWidth + 20 + 16, y: y + 16, width: cardWidth - 32, alignment: .left)
            _ = drawText(average.toCurrency(), font: .systemFont(ofSize: 24, weight: .bold), color: .black, x: margin + cardWidth + 20 + 16, y: y + 40, width: cardWidth - 32, alignment: .left)

            y += 120

            // MARK: - People & Items Section

            _ = drawText("PEOPLE & ITEMS", font: .systemFont(ofSize: 13, weight: .bold), color: darkGray, x: margin, y: y, width: pageWidth - 2 * margin)
            y += 30

            for person in people {
                checkNewPage()

                // Person card
                let personCardHeight: CGFloat = 60
                drawRoundedRect(x: margin, y: y, width: pageWidth - 2 * margin, height: personCardHeight, radius: 10, fillColor: lightGray)

                // Avatar circle (green)
                drawCircle(x: margin + 30, y: y + 30, radius: 18, fillColor: brandGreen)
                let initial = String(person.name.prefix(1)).uppercased()
                _ = drawText(initial, font: .systemFont(ofSize: 14, weight: .bold), color: .white, x: margin + 30 - 8, y: y + 30 - 7, width: 16, alignment: .center)

                // Name
                _ = drawText(person.name, font: .systemFont(ofSize: 16, weight: .semibold), color: .black, x: margin + 60, y: y + 18, width: 200, alignment: .left)

                // Amount
                _ = drawText(person.amount.toCurrency(), font: .systemFont(ofSize: 18, weight: .bold), color: .black, x: pageWidth - margin - 150, y: y + 18, width: 140, alignment: .right)

                y += personCardHeight + 12

                // Items for this person
                let personItems = items.filter { $0.personId == person.id }
                if !personItems.isEmpty {
                    for item in personItems {
                        checkNewPage()

                        drawRoundedRect(x: margin + 20, y: y, width: pageWidth - 2 * margin - 40, height: 40, radius: 8, fillColor: .white, strokeColor: lightGray)

                        _ = drawText("• \(item.name)", font: .systemFont(ofSize: 13, weight: .regular), color: .black, x: margin + 36, y: y + 12, width: 300, alignment: .left)

                        let itemText = item.quantity > 1 ? "\(item.price.toCurrency()) x\(item.quantity)" : item.price.toCurrency()
                        _ = drawText(itemText, font: .systemFont(ofSize: 13, weight: .semibold), color: .black, x: pageWidth - margin - 180, y: y + 12, width: 140, alignment: .right)

                        y += 48
                    }
                } else {
                    checkNewPage()
                    drawRoundedRect(x: margin + 20, y: y, width: pageWidth - 2 * margin - 40, height: 40, radius: 8, fillColor: .white, strokeColor: lightGray)
                    _ = drawText("No items", font: .systemFont(ofSize: 13, weight: .regular), color: darkGray, x: margin + 36, y: y + 12, width: 300, alignment: .left)
                    y += 48
                }

                y += 10
            }

            // MARK: - Extras/Adjustments Section

            if !adjustments.isEmpty {
                y += 10
                _ = drawText("EXTRAS", font: .systemFont(ofSize: 13, weight: .bold), color: darkGray, x: margin, y: y, width: pageWidth - 2 * margin)
                y += 30

                for adj in adjustments {
                    drawRoundedRect(x: margin, y: y, width: pageWidth - 2 * margin, height: 50, radius: 10, fillColor: .white, strokeColor: lightGray)

                    _ = drawText(adj.name, font: .systemFont(ofSize: 15, weight: .semibold), color: .black, x: margin + 16, y: y + 12, width: 250, alignment: .left)

                    let adjLabel = adj.isDiscount ? "Discount" : "Charge"
                    _ = drawText(adjLabel, font: .systemFont(ofSize: 11, weight: .regular), color: adj.isDiscount ? .systemRed : darkGray, x: margin + 16, y: y + 30, width: 100, alignment: .left)

                    let adjAmount = (adj.isDiscount ? -adj.amount : adj.amount).toCurrency()
                    _ = drawText(adjAmount, font: .systemFont(ofSize: 16, weight: .bold), color: adj.isDiscount ? .systemRed : .black, x: pageWidth - margin - 150, y: y + 16, width: 140, alignment: .right)

                    y += 60
                }
            }

            // MARK: - Footer

            let footerY = pageHeight - margin - 20
            _ = drawText("Generated by Splitin", font: .systemFont(ofSize: 10, weight: .regular), color: darkGray, x: margin, y: footerY, width: pageWidth - 2 * margin, alignment: .center)
        }

        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("Splitin-\(Date().timeIntervalSince1970).pdf")
        try data.write(to: tempURL)
        return tempURL
    }

    // MARK: - Generate PDF from BillHistory

    static func generateFromHistory(bill: BillHistory, banks: [BankAccount]) throws -> URL {
        let pageWidth: CGFloat  = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat     = 40
        let brandBlue  = UIColor(red: 0.145, green: 0.388, blue: 0.922, alpha: 1.0) // #2563EB
        let lightGray  = UIColor(red: 0.95,  green: 0.95,  blue: 0.95,  alpha: 1.0)
        let midGray    = UIColor(red: 0.55,  green: 0.55,  blue: 0.55,  alpha: 1.0)
        let darkText   = UIColor(red: 0.12,  green: 0.18,  blue: 0.27,  alpha: 1.0)
        let greenColor = UIColor(red: 0.13,  green: 0.70,  blue: 0.37,  alpha: 1.0)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            let context = ctx.cgContext
            var y: CGFloat = 0
            let contentWidth = pageWidth - 2 * margin

            // MARK: Helpers

            func drawRect(_ rect: CGRect, fill: UIColor, radius: CGFloat = 0, stroke: UIColor? = nil) {
                let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
                context.saveGState()
                fill.setFill(); path.fill()
                if let s = stroke { s.setStroke(); path.lineWidth = 0.5; path.stroke() }
                context.restoreGState()
            }

            @discardableResult
            func drawText(_ text: String, font: UIFont, color: UIColor,
                          x: CGFloat, y: CGFloat, width: CGFloat,
                          align: NSTextAlignment = .left) -> CGFloat {
                let para = NSMutableParagraphStyle()
                para.alignment = align
                para.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color, .paragraphStyle: para]
                let str = NSAttributedString(string: text, attributes: attrs)
                let rect = CGRect(x: x, y: y, width: width, height: .greatestFiniteMagnitude)
                let size = str.boundingRect(with: rect.size, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                str.draw(with: rect, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil)
                return size.height
            }

            // MARK: Header
            let headerH: CGFloat = 130
            drawRect(CGRect(x: 0, y: 0, width: pageWidth, height: headerH), fill: brandBlue)

            let dateFmt = DateFormatter()
            dateFmt.dateStyle = .medium; dateFmt.timeStyle = .short

            // Avatar (left side, vertically centered)
            let avatarR: CGFloat = 38
            let avatarCX: CGFloat = margin + avatarR
            let avatarCY: CGFloat = headerH / 2
            let avatarRect = CGRect(x: avatarCX - avatarR, y: avatarCY - avatarR,
                                    width: avatarR * 2, height: avatarR * 2)

            if let profileImg = ProfileImageStore.load() {
                context.saveGState()
                UIBezierPath(ovalIn: avatarRect).addClip()
                profileImg.draw(in: avatarRect)
                context.restoreGState()
            } else {
                context.saveGState()
                UIColor.white.withAlphaComponent(0.25).setFill()
                UIBezierPath(ovalIn: avatarRect).fill()
                context.restoreGState()
                let initial = String((UserDefaults.standard.string(forKey: "userName") ?? "S").prefix(1)).uppercased()
                drawText(initial, font: .systemFont(ofSize: 28, weight: .bold), color: .white,
                         x: avatarCX - avatarR, y: avatarCY - 17, width: avatarR * 2, align: .center)
            }

            // White circle border
            context.saveGState()
            UIColor.white.withAlphaComponent(0.4).setStroke()
            let borderPath = UIBezierPath(ovalIn: avatarRect)
            borderPath.lineWidth = 1.5
            borderPath.stroke()
            context.restoreGState()

            // Right side: SPLITIN → bill name → date
            let textX = avatarCX + avatarR + 16
            let textW = pageWidth - textX - margin
            drawText("SPLITIN", font: .systemFont(ofSize: 11, weight: .bold),
                     color: UIColor.white.withAlphaComponent(0.7), x: textX, y: 24, width: textW)
            drawText(bill.title.isEmpty ? "Bill Summary" : bill.title,
                     font: .systemFont(ofSize: 24, weight: .bold),
                     color: .white, x: textX, y: 42, width: textW)
            drawText(dateFmt.string(from: bill.date),
                     font: .systemFont(ofSize: 11), color: UIColor.white.withAlphaComponent(0.85),
                     x: textX, y: 96, width: textW)
            y = 150

            // MARK: Summary Cards
            let cardW = (contentWidth - 24) / 3
            let cards: [(String, String)] = [
                ("TOTAL BILL",  bill.totalAmount.toCurrency()),
                ("PEOPLE",      "\(bill.people.count)"),
                ("COLLECTED",   bill.people.filter { $0.isPaid }.reduce(0) { $0 + $1.amount }.toCurrency())
            ]
            for (i, card) in cards.enumerated() {
                let cx = margin + CGFloat(i) * (cardW + 12)
                drawRect(CGRect(x: cx, y: y, width: cardW, height: 76), fill: .white, radius: 10, stroke: lightGray)
                drawText(card.0, font: .systemFont(ofSize: 9, weight: .semibold), color: midGray,
                         x: cx + 10, y: y + 12, width: cardW - 20)
                drawText(card.1, font: .systemFont(ofSize: 17, weight: .bold), color: darkText,
                         x: cx + 10, y: y + 32, width: cardW - 20)
            }
            y += 96

            // MARK: People Section
            drawText("PEOPLE", font: .systemFont(ofSize: 11, weight: .bold), color: midGray,
                     x: margin, y: y, width: contentWidth)
            y += 22

            for person in bill.people {
                if y > pageHeight - 120 { ctx.beginPage(); y = margin }
                let rowH: CGFloat = 52
                let bgColor = person.isPaid ? UIColor(red: 0.93, green: 0.99, blue: 0.95, alpha: 1) : lightGray
                drawRect(CGRect(x: margin, y: y, width: contentWidth, height: rowH), fill: bgColor, radius: 10)

                // Avatar circle
                let avatarColor = person.isPaid ? greenColor : brandBlue
                drawRect(CGRect(x: margin + 10, y: y + 10, width: 32, height: 32), fill: avatarColor, radius: 16)
                drawText(String(person.name.prefix(1)).uppercased(),
                         font: .systemFont(ofSize: 13, weight: .bold), color: .white,
                         x: margin + 10, y: y + 18, width: 32, align: .center)

                // Name
                drawText(person.name, font: .systemFont(ofSize: 14, weight: .semibold), color: darkText,
                         x: margin + 52, y: y + 10, width: 200)

                // Paid badge
                let badgeText = person.isPaid ? "✓ Paid" : "Unpaid"
                let badgeColor = person.isPaid ? greenColor : UIColor.systemOrange
                drawText(badgeText, font: .systemFont(ofSize: 11, weight: .medium), color: badgeColor,
                         x: margin + 52, y: y + 30, width: 120)

                // Amount
                drawText(person.amount.toCurrency(),
                         font: .systemFont(ofSize: 15, weight: .bold), color: darkText,
                         x: margin, y: y + 16, width: contentWidth - 10, align: .right)

                y += rowH + 8
            }
            y += 10

            // MARK: Bank Info Section
            if !banks.isEmpty {
                if y > pageHeight - 160 { ctx.beginPage(); y = margin }

                drawText("PAYMENT INFO", font: .systemFont(ofSize: 11, weight: .bold), color: midGray,
                         x: margin, y: y, width: contentWidth)
                y += 22

                for bank in banks {
                    if y > pageHeight - 80 { ctx.beginPage(); y = margin }
                    let bankRowH: CGFloat = 56
                    drawRect(CGRect(x: margin, y: y, width: contentWidth, height: bankRowH),
                             fill: UIColor(red: 0.94, green: 0.96, blue: 1.0, alpha: 1), radius: 10,
                             stroke: UIColor(red: 0.145, green: 0.388, blue: 0.922, alpha: 0.2))

                    // Bank icon placeholder
                    drawRect(CGRect(x: margin + 10, y: y + 10, width: 36, height: 36),
                             fill: brandBlue.withAlphaComponent(0.15), radius: 8)
                    drawText("🏦", font: .systemFont(ofSize: 18),
                             color: brandBlue, x: margin + 10, y: y + 16, width: 36, align: .center)

                    drawText(bank.bankName, font: .systemFont(ofSize: 14, weight: .semibold), color: darkText,
                             x: margin + 56, y: y + 10, width: contentWidth - 66)
                    let maskedNum = bank.accountNumber.count > 4
                        ? "•••• \(bank.accountNumber.suffix(4))"
                        : bank.accountNumber
                    drawText("\(maskedNum)  ·  \(bank.accountName)",
                             font: .systemFont(ofSize: 12), color: midGray,
                             x: margin + 56, y: y + 30, width: contentWidth - 66)
                    y += bankRowH + 8
                }
            }

            // MARK: Footer
            let footerY = pageHeight - margin - 16
            drawRect(CGRect(x: 0, y: footerY - 8, width: pageWidth, height: 1), fill: lightGray)
            drawText("Generated by Splitin  ·  \(dateFmt.string(from: Date()))",
                     font: .systemFont(ofSize: 9), color: midGray,
                     x: margin, y: footerY, width: contentWidth, align: .center)
        }

        let fileName = (bill.title.isEmpty ? "Bill" : bill.title)
            .replacingOccurrences(of: " ", with: "_")
        let tempURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("Splitin-\(fileName)-\(Int(Date().timeIntervalSince1970)).pdf")
        try data.write(to: tempURL)
        return tempURL
    }
}
